### ISSUE TITLE
Update to liveproxy v0.3.0 and streamlink lib to v1.3.0 for Kodi Leia/Matrix

### ISSUE THREAD

**Issue by teleboy5** [back-to/repo#1]
Hello, 
are there an update of Kodi related repo/zip to newest streamlink lib versions?
Currently, Kodi's script.module.streamlink provided with streamlink lib version v1.0.0, Kodi's addon liveproxy at version 0.1.1

Thx for your support.

**Comment by back-to** [comment]
updated it,
but I did only a quick test on Windows with Kodi Leia.

seems to work.
